language: php
php:
- '5.5'
before_install:
- openssl aes-256-cbc -K $encrypted_e2bda422f317_key -iv $encrypted_e2bda422f317_iv
  -in client-secret.json.enc -out client-secret.json -d
before_deploy:
- env | grep TELEGRAM_TOKEN > env
- env | grep GOOGLE_APIKEY >> env
cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/gcloud/google-cloud-sdk"
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
env:
- GOOGLE_PROJECT_ID=schettbott
install:
- composer install
script: "/bin/true"
sudo: false
env:
  global:
  - secure: X83fsoeKND5dp86lgQeVuw1ORyTIa3BDd36FDYpl6bePcOo7uTu25PZT5B+Fb3qV2qNFrYfaMBeTJXE3juak7/MeK1/VjvWesi61GbBUkvqfSrqwEti++0xXPA/r29T3VXh4GTwP56zBwGelpg+gOlhUDbKKjrGCgv6ZHja1n0BqEu2qZbspifhYaBlWJr45498qYbO938Tyyb3p6uNja4ml8eEttehIQQfJWKqHe+NPCIp17ImW8lSOy+bq0JVjA1TgGIjGRE6uH2+K128sHMFqIiMk3JztL+IUeLM3go6tqShL7SrPYDWf2kjdg8HcU/PfUfotm+SH879R2XmfusQJ8S9gVVXLnk1iwgiF5umClM0XBF+qxr71K1lOFVji0gCGSyx6NfM8b1cFO3Q1UveoXqsRt7wdzlMHbusZXm5VJiJ5ZFvSuvqL9abHBucMt6VjfRPp+YUdROscXWq9+sdjuSSfQpsjSo+G8Wt8aU29Wg++B1WL6l7IN1nUZylzE7V0YF4S5RqeWsolNmy6Oyf0AhZW5Uwbmg94oi2zxKL4EcPLfGp5iodc0IqMwWlhbMSM/JAy0uTXM7yRDhtsw9TVs7K9+neuMEYppeDCiEOPz75m9LAI511cgPFN0Dc04oZ8dojvyious4uxYAH9qJiVdvaTn9A76bMQdCKAXFk=
  - secure: NDodTBza5jmPGbhUZnKWVDsufR832yqv/j8b2H4tVY6JfObdBDk7NeTL6xKH6zGSnDTg3t6pQe8bVhrw/FFBuvVNqT5LyQA6kZIt/FhLcwoBeuW3bmXUf6j98npIlDh0QQH9eUQbuV5pFWfylVljhB4uA9DEX3YKfJWcY/uYxIPOW28oCjXUIa+XlyYRzDYsLi4XIfckLGWFmpRsiZnf5vhanYwzkzk4pXG8rTSQHnnqTC3XA/xUn96UtcuUEW3tQgPjIyRHe0BsMewpOGb4KV8/lHOkNwz2T62clJvo6PKP3XAA18FR99PBUued+aY5+HIPVXmpSWCEYsHedJ623J1NHe9G895Iwe7i7zMgEvWxIlM7xld362jRP27VJr7yJHKK9sCoDnDq2zCv6eo8BXPgHYekpx3wyMP5MeTII9/mxd0XyMxnu6xpJHRbsQCmCo8mfQ94XlYoSD2DIkJX18lbXoNsth2dj7KzuK96TRK98CyznX5z8Ka0osV1Oeq64TQXffQ1xlH/P53qkZomqwHs+kSDb7/pRFyKmdEqBTLNb2i/QmMAqoRMWnxVga/28vbMytyjJ041BF0+KQ66IBgFeL92ovTljN9yGGQp7NGqdQYhwA3PJ90bO5dKu3ujrMwfyR2FMY59FUB+G9yWsHqiiP9RcKLtSPPF5RcKNMY=
